# Generated by Django 5.1.3 on 2024-11-29 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('CourseTitle', models.TextField(primary_key=True, serialize=False)),
                ('ProgramLvl', models.TextField()),
                ('TuitionFees', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('UniversityName', models.TextField(primary_key=True, serialize=False)),
                ('State', models.TextField()),
                ('Course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Assignment2.course')),
            ],
        ),
    ]
