# Generated by Django 5.1.3 on 2024-11-29 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Assignment2', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='university',
            name='Course',
        ),
        migrations.AddField(
            model_name='course',
            name='CourseID',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='university',
            name='UniversityID',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='course',
            name='CourseTitle',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='university',
            name='UniversityName',
            field=models.TextField(),
        ),
    ]
