# Generated by Django 5.1.3 on 2024-11-29 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Assignment2', '0002_remove_university_course_course_courseid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='Course',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Assignment2.course'),
            preserve_default=False,
        ),
    ]
