# Generated by Django 5.1.3 on 2024-11-30 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Assignment2', '0003_university_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='university',
            name='Course',
        ),
        migrations.CreateModel(
            name='UniversityCourse',
            fields=[
                ('UniversityCourseID', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('CourseID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Assignment2.course')),
                ('UniversityID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Assignment2.university')),
            ],
        ),
    ]
