# Generated by Django 5.1.3 on 2024-12-01 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Assignment2', '0004_remove_university_course_universitycourse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='CourseID',
        ),
        migrations.RemoveField(
            model_name='universitycourse',
            name='UniversityCourseID',
        ),
        migrations.AddField(
            model_name='course',
            name='CourseCode',
            field=models.TextField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='universitycourse',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
