# Generated by Django 5.1.3 on 2024-12-01 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Assignment2', '0005_remove_course_courseid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='universitycourse',
            old_name='CourseID',
            new_name='CourseCode',
        ),
    ]
