# Generated by Django 5.1.3 on 2024-12-01 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Assignment2', '0006_rename_courseid_universitycourse_coursecode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='UniversityID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
