# Generated by Django 5.1.3 on 2024-12-03 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Assignment2', '0008_rename_coursecode_universitycourse_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='CourseID',
            field=models.TextField(null=True),
        ),
    ]
