# Generated by Django 5.1.3 on 2024-12-03 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Assignment2', '0009_course_courseid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='CourseCode',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='course',
            name='CourseID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
