# Generated by Django 5.1.3 on 2024-12-03 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Assignment2', '0010_alter_course_coursecode_alter_course_courseid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('AdminID', models.AutoField(primary_key=True, serialize=False)),
                ('Username', models.CharField(max_length=255, unique=True)),
                ('Password', models.CharField(max_length=255)),
                ('Token', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
